### ISSUE TITLE
run the webui using code?not UI?

### ISSUE THREAD

**Issue by henbucuoshanghai** [dsymbol/stable-diffusion-webui-colab#1]

**Comment by dsymbol** [comment]
This should help you out https://github.com/CompVis/stable-diffusion#text-to-image-with-stable-diffusion

**Comment by henbucuoshanghai** [comment]
kind answer,but why  -prompt "a photograph of an astronaut riding a horse",  not the webui like "1girl,seaside,boat"

**Comment by dsymbol** [comment]
Sorry I'm unsure only used it on the web ui consider asking in the discord https://discord.com/invite/stablediffusion
